# Generated by Django 6.0.3 on 2026-03-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anketin', '0002_alter_soru_yayinlanma_tarihi'),
    ]

    operations = [
        migrations.AddField(
            model_name='soru',
            name='kategori',
            field=models.CharField(choices=[('Spor', 'Spor'), ('Teknoloji', 'Teknoloji'), ('Finans', 'Finans'), ('Oyun', 'Oyun'), ('Gündem', 'Gündem'), ('Sinema', 'Sinema'), ('Diğer', 'Diğer')], default='Diğer', max_length=20),
        ),
    ]
