# Generated by Django 6.0.3 on 2026-03-25 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anketin', '0004_kullaniciprofili'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kullaniciprofili',
            name='cozulen_anket_sayisi',
            field=models.IntegerField(default=0, verbose_name='Toplam Çözülen Anket'),
        ),
        migrations.AddField(
            model_name='kullaniciprofili',
            name='favori_anketler',
            field=models.ManyToManyField(blank=True, related_name='favorileyen_kullanicilar', to='anketin.soru'),
        ),
        migrations.AddField(
            model_name='kullaniciprofili',
            name='profil_fotografi',
            field=models.ImageField(blank=True, default='default_avatar.png', null=True, upload_to='profil_fotograflari/'),
        ),
        migrations.AddField(
            model_name='kullaniciprofili',
            name='puan',
            field=models.IntegerField(default=0, verbose_name='Kazanılan Puan'),
        ),
        migrations.AddField(
            model_name='soru',
            name='olusturan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kendi_anketleri', to=settings.AUTH_USER_MODEL),
        ),
    ]
