# Generated by Django 6.0.3 on 2026-03-26 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anketin', '0005_kullaniciprofili_cozulen_anket_sayisi_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Oy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('secenek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anketin.secenek')),
                ('soru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anketin.soru')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'soru'), name='unique_user_vote'), models.UniqueConstraint(condition=models.Q(('session_id__isnull', False)), fields=('session_id', 'soru'), name='unique_session_vote')],
            },
        ),
    ]
